export enum condiments {
    AIL = 'ail',
    BASILIC = 'basilic',
    BOUQUET_GARNI = 'bouquet garni',
    CANNELLE = 'cannelle',
    CARDAMOME = 'cardamome',
    CHILI = 'chili',
    CIBOULETTE = 'ciboulette',
    CORIANDRE = 'coriandre',
    CUMIN = 'cumin',
    CURCUMA = 'curcuma',
    ECHALOTES = 'échalotes',
    FINES_HERBES = 'fines herbes',
    GINGEMBRE = 'gingembre',
    HUILE_ARACHIDE = 'huile d\'arachide',
    HUILE_OLIVE = 'huile d\'olive',
    HUILE_TOURNESOL = 'huile de tournesol',
    LAURIER = 'laurier',
    MENTHE = 'menthe',
    MOUTARDE = 'moutarde',
    MUSCADE = 'muscade',
    MUSCADE_NOIX = 'noix de muscade',
    OIGNONS = 'oignons',
    OIGNONS_BLANCS = 'oignons blancs',
    OIGNONS_JAUNES = 'oignons jaunes',
    OIGNONS_JEUNES = 'oignons de printemps',
    OIGNONS_ROUGES = 'oignons rouges',
    PAPRIKA = 'paprika',
    PAPRIKA_DOUX = 'paprika doux',
    PAPRIKA_FORT = 'paprika fort',
    PERSIL = 'persil',
    PIMENT = 'piment',
    PIMENT_CAYENNE = 'piment de Cayenne',
    PIMENT_ESPELETTE = 'piment d\'Espelette',
    PIMENT_JALAPENO = 'piment Jalapeño',
    POIVRE = 'poivre',
    ROMARIN = 'romarin',
    SAUGE = 'sauge',
    SEL = 'sel',
    SUCRE = 'sucre',
    // dans le Nord, la cassonade c'est la vergoise. na.
    SUCRE_CASSONADE = 'vergeoise',
    SUCRE_GLACE = 'sucre glace',
    SUCRE_ROUX = 'sucre roux',
    THYM = 'thym',
    VINAIGRE = 'vinaigre',
    VINAIGRE_BALSAMIQUE = 'vinaigre balsamique',
    VINAIGRE_CIDRE = 'vinaigre de cidre',
    VINAIGRE_VIN_ROUGE = 'vinaigre de vin rouge',
};

export enum viande {
    BOEUF = 'boeuf',
    BOEUF_A_MIJOTER = 'viande de boeuf à mijoter',
    BOEUF_A_MIJOTER_BOURGUIGNON = 'boeuf bourguignon (morceaux persillés et un peu gélatineux)',
    BOEUF_HACHE = 'boeuf haché',
    BOEUF_JOUE = 'joue de boeuf',
    CANARD_CONFIT = 'confit de canard',
    CANARD_CONFIT_CUISSE = 'cuisse de canard confite',
    CHORIZO = 'chorizo',
    DINDE_AIGUILLETTES = 'aiguillettes de dinde',
    DINDE_ESCALOPES = 'escalopes de dinde',
    DINDE_FILETS = 'filets de dinde',
    DINDE_PAUPIETTES = 'paupiettes de dinde',
    JAMBON = 'jambon',
    JAMBON_BLANC = 'jambon blanc',
    JAMBON_FUME = 'jambon fumé',
    LARDONS = 'lardons',
    PORC = 'porc',
    PORC_COTES = 'côtes de porc',
    PORC_JOUE = 'joue de porc',
    POULET = 'poulet',
    POULET_AIGUILLETTES = 'aiguillettes de poulet',
    POULET_AILES = 'ailes de poulet',
    POULET_BLANC = 'blancs de poulet',
    POULET_CUISSES = 'cuisses de poulet',
    SALAMELLE = 'salamelle de Mantoue',
    SAUCISSES = 'saucisses',
    SAUCISSES_MONTBELIARD = 'saucisses de Montbéliard',
    SAUCISSES_MORTAUX = 'saucisses de Mortaux',
    SAUCISSES_STRASBOURG = 'saucisses de Strasbourg',
    VEAU = 'veau',
};

export enum poisson {
    CABILLAUD = 'cabillaud',
    LIEU = 'lieu',
    LIEU_JAUNE = 'lieu jaune',
    LIEU_NOIR = 'lieu noir',
    LIMANDE = 'limande',
    ROUGET = 'rouget',
    SOLE = 'sole',
    THON = 'thon',
};

export enum feculents {
    FARINE_BLE = 'farine',
    FARINE_MAIS = 'farine de maïs',
    HARICOTS_ROUGES = 'haricots rouges',
    LENTILLES_BLONDES = 'lentilles blondes',
    LENTILLES_CORAIL = 'lentilles corail',
    LENTILLES_VERTES = 'lentilles vertes',
    // on considère les patates comme à la fois des légumes et des féculents
    PATATES = 'pommes de terre',
    PATES = 'pâtes',
    QUINOA = 'quinoa',
    RIZ = 'riz',
    RIZ_BASMATI = 'riz Basmati',
    RIZ_RISOTTO = 'riz risotto',
    RIZ_RISOTTO_ARBORIO = 'riz arborio (crémeux)',
    RIZ_RISOTTO_BALDO = 'riz baldo (absorbant)',
    RIZ_RISOTTO_CARNAROLI = 'riz carnaroli',
    RIZ_RISOTTO_ROMA = 'riz roma (polyvalent)',
    RIZ_RISOTTO_VIALONE = 'riz vialone nano',
    RIZ_ROND = 'riz rond',
    RIZ_THAI = 'ris thaï',
    SEMOULE = 'semoule',
}

export enum fromages {
    CHEDDAR = 'cheddar',
    COMTE = 'comte',
    GORGONZOLA = 'gorgonzola',
    GRANA = 'grana padano',
    GRUYERE = 'gruyère',
    MASCARPONE = 'mascarpone',
    MOZZARELLA = 'mozzarella',
    PARMESAN = 'parmesan',
}

export enum legumes {
    AUBERGINES = 'aubergines',
    BETTERAVES = 'betteraves',
    BETTERAVES_CUITES = 'betteraves cuites',
    BUTTERNUT = 'butternut',
    CAROTTES = 'carottes',
    CELERI = 'céleri',
    CHOU = 'chou',
    CHOU_ROUGE = 'chou rouge',
    COURGE = 'courge',
    COURGETTES = 'courgettes',
    COURGETTES_RONDES = 'courgettes rondes',
    LEGUMES_COUSCOUS = 'légumes à couscous',
    MAIS = 'maïs',
    NAVET = 'navet',
    // on considère les patates comme à la fois des légumes et des féculents
    PATATES = 'pommes de terre',
    POIREAU = 'poireaux',
    POIVRON = 'poivrons',
    POIVRON_JAUNE = 'poivrons jaunes',
    POIVRON_ROUGE = 'poivrons rouges',
    POIVRON_VERT = 'poivrons verts',
    POTIRON = 'potiron',
    RADIS = 'radis',
    RADIS_NOIR = 'radis noir',
    RAIFORT = 'raifort',
    SALSIFI = 'salsifi',
    TOMATES = 'tomates',
    TOMATES_CERISE = 'tomates cerise',
    TOMATES_CONCENTRE = 'concentré de tomates',
    TOMATES_COULIS = 'coulis de tomates',
    TOMATES_PULPE = 'pulpe de tomates',
    TOMATES_PUREE = 'purée de tomates',
    TOMATES_SECHEES = 'tomates séchées',
    TOPINAMBOUR = 'tompinambour',
};

export enum misc {
    BOUILLON_CUBE = 'bouillon cube',
    BOUILLON_CUBE_BOEUF = 'bouillon cube de boeuf',
    BOUILLON_CUBE_VOLAILLE = 'bouillon cube de volaille',
    BOUILLON_LEGUMES = 'bouillon de légumes',
    CHAMPI = 'champignons',
    CHAMPI_CEPES = 'cèpes',
    CHAMPI_GIROLLES = 'girolles',
    CHAMPI_PARIS = 'champignons de Paris',
    CORNICHONS = 'cornichons',
    EAU = 'eau',
    GELATINE = 'feuilles de gélatine',
    LEVURE_BOULANGER = 'levure de boulanger',
    LEVURE_CHIMIQUE = 'levure chimique',
    OEUFS = 'oeufs',
    PAIN = 'pain',
    PAIN_COMPLET = 'pain complet',
    PAIN_MIE = 'pain de mie',
    SPECULOOS = 'biscuits speculoos',
    TORTILLAS = 'tortillas',
}

export enum laitages_divers {
    BEURRE = 'beurre',
    BEURRE_DEMI_SEL = 'beurre demi-sel',
    CREME_AIGRE = 'crème aigre',
    CREME_FRAICHE = 'crème fraîche',
    CREME_LIQUIDE = 'crème liquide',
    LAIT = 'lait',
}

export enum surgeles {
    EPINARDS = 'épinards surgelés',
    GRIOTTES = 'griottes surgelées',
    LASAGNES = 'lasagnes surgelées',
    MOUSSAKA = 'moussaka surgelée',
    POISSON_BORDELAISE = 'poisson bordelaise surgelé',
    POISSON_BRANDADE = 'brandade de morue surgelée'
}

export enum alcool {
    BIERE_BLONDE = 'bière blonde',
    BIERE_BRUNE = 'bière brune',
    EAU_DE_VIE_POIRE = 'eau de vie de poire',
    EAU_DE_VIE_PRUNE = 'eau de vie de prune',
    VIN_BLANC_MONBAZILLAC = 'monbazillac',
    VIN_BLANC_SEC = 'vin blanc sec',
    VIN_ROUGE = 'vin rouge',
    VIN_ROUGE_BEAUJOLAIS = 'beaujolais',
    VIN_ROUGE_BORDEAUX = 'bordeaux rouge',
    VIN_ROUGE_BOURGOGNE = 'bourgogne rouge',
    VIN_ROUGE_COTES_RHONE = 'côtes du rhône rouge',
    VIN_ROUGE_LOIRE = 'vin de loire rouge',
}

export enum pates {
    FARFALLE = 'farfalle',
    FUSILLI = 'fusilli',
    LINGUINE = 'linguine',
    PENNE = 'penne rigate',
    RADIATORI = 'radiatori',
    SPAGHETTI = 'spaghetti',
    TAGLIATELLE = 'tagliatelle',
}

export enum fruits {
    BANANES = 'bananes',
    CERISES = 'cerises',
    CITRONS = 'citrons',
    FRAMBOISES = 'framboises',
    FRUITS_ROUGES_DIVERS = 'fruits rouges',
    GRIOTTES = 'griottes',
    GROSEILLES = 'groseilles',
    KIWIS = 'kiwis',
    ORANGES = 'oranges',
    POIRES = 'poires',
    POMMES = 'pommes',
}

export enum cereales {
    BLE = 'blé',
    MAIS = 'maïs',
    ORGE = 'orge',
    SARRASIN = 'sarrasin',
    SEIGLE = 'seigle',
}